In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

from sklearn.preprocessing import MinMaxScaler

import matplotlib.pyplot as plt

In [2]:
PROJECT_ROOT = Path("..")

GEO_PATH = (
    PROJECT_ROOT /
    "data" /
    "geo" /
    "datafile.csv"
)

geo_df = pd.read_csv(GEO_PATH)

geo_df.head()

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,Nicobars,Andaman & Nicobar Islands,882,764,125,78.0,23.0,973,927,98.0,...,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,North & Middle Andaman,Andaman & Nicobar Islands,874,789,108,82.7,19.8,950,844,100.0,...,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,South Andaman,Andaman & Nicobar Islands,868,844,134,84.7,21.0,967,935,96.5,...,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8
3,Srikakulam,Andhra Pradesh,874,780,100,60.0,20.7,1140,1163,95.0,...,14.4,5.5,22.9,1.0,0.2,3.8,7.1,21.3,0.6,28.3
4,Vizianagaram,Andhra Pradesh,902,853,134,56.0,20.6,1114,898,95.4,...,14.8,6.4,25.1,4.9,0.6,7.3,11.4,21.5,0.8,32.3

In [3]:
print("="*60)
print("Geo Dataset")
print("="*60)

print(geo_df.shape)

geo_df.info()

============================================================
Geo Dataset
============================================================
(706, 109)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 706 entries, 0 to 705
Columns: 109 entries, District Names to Men age 15 years and above who consume alcohol (%)
dtypes: float64(54), int64(4), object(51)
memory usage: 601.3+ KB

In [4]:
missing = geo_df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [11]:
selected_columns = [

    "District Names",

    "State/UT",

    "Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)",

    "Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)",

    "Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%)",

    "All women age 15-49 years who are anaemic22 (%)"

]

geo_selected = geo_df[selected_columns]

geo_selected.head()

,District Names,State/UT,Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%),Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%),All women age 15-49 years who are anaemic22 (%)
0,Nicobars,Andaman & Nicobar Islands,8.2,37.7,38.4,38.3
1,North & Middle Andaman,Andaman & Nicobar Islands,8.6,30.4,62.5,62.1
2,South Andaman,Andaman & Nicobar Islands,10.0,43.4,57.6,57.7
3,Srikakulam,Andhra Pradesh,13.8,59.6,62.8,62.6
4,Vizianagaram,Andhra Pradesh,16.9,66.7,64.6,64.0

In [12]:
geo_selected.columns = [

    "District",

    "State",

    "Low_BMI",

    "Child_Anemia",

    "NonPregnant_Women_Anemia",

    "Women_Anemia"

]

geo_selected.head()

,District,State,Low_BMI,Child_Anemia,NonPregnant_Women_Anemia,Women_Anemia
0,Nicobars,Andaman & Nicobar Islands,8.2,37.7,38.4,38.3
1,North & Middle Andaman,Andaman & Nicobar Islands,8.6,30.4,62.5,62.1
2,South Andaman,Andaman & Nicobar Islands,10.0,43.4,57.6,57.7
3,Srikakulam,Andhra Pradesh,13.8,59.6,62.8,62.6
4,Vizianagaram,Andhra Pradesh,16.9,66.7,64.6,64.0

In [13]:
geo_selected["Geo_Risk"] = (

    0.50 * geo_selected["Women_Anemia"]

    +

    0.30 * geo_selected["Child_Anemia"]

    +

    0.20 * geo_selected["Low_BMI"]

)

TypeError: can't multiply sequence by non-int of type 'float'

In [8]:
for col in geo_df.columns:
    if "bmi" in col.lower():
        print(col)

Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)
Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%)

In [9]:
for col in geo_df.columns:
    if "children" in col.lower():
        print(col)

Sex ratio at birth for children born in the last five years (females per 1,000 males)
Children under age 5 years whose birth was registered with the civil authority (%)
Children age 5 years who attended pre-primary school during the school year 2019-20 (%)
Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%)
Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)
Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)
Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%)
Children age 12-23 months who have received BCG (%)
Children age 12-23 months who have received 3 doses of polio vaccine13 (%)
Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%)
Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%)
Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%)
Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%)
Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%)
Children age 9-35 months who received a vitamin A dose in the last 6 months (%)
Children age 12-23 months who received most of their vaccinations in a public health facility (%)
Children age 12-23 months who received most of their vaccinations in a private health facility (%)
Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%)
Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%)
Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%)
Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)
Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%)
Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)
Children under age 3 years breastfed within one hour of birth15 (%)
Children under age 6 months exclusively breastfed16 (%)
Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%)
Breastfeeding children age 6-23 months receiving an adequate diet16, 17  (%)
Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)
Total children age 6-23 months receiving an adequate diet16, 17  (%)
Children under 5 years who are stunted (height-for-age)18 (%)
Children under 5 years who are wasted (weight-for-height)18 (%)
Children under 5 years who are severely wasted (weight-for-height)19 (%)
Children under 5 years who are underweight (weight-for-age)18 (%)
Children under 5 years who are overweight (weight-for-height)20 (%)
Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)

In [10]:
print(list(geo_df.columns))

['District Names', 'State/UT', 'Number of Households surveyed', 'Number of Women age 15-49 years interviewed', 'Number of Men age 15-54 years interviewed', 'Female population age 6 years and above who ever attended school (%)', 'Population below age 15 years (%)', ' Sex ratio of the total population (females per 1,000 males)', 'Sex ratio at birth for children born in the last five years (females per 1,000 males)', 'Children under age 5 years whose birth was registered with the civil authority (%)', 'Deaths in the last 3 years registered with the civil authority (%)', 'Population living in households with electricity (%)', 'Population living in households with an improved drinking-water source1 (%)', 'Population living in households that use an improved sanitation facility2 (%)', 'Households using clean fuel for cooking3 (%)', 'Households using iodized salt (%)', 'Households with any usual member covered under a health insurance/financing scheme (%)', 'Children age 5 years who attended pre-primary school during the school year 2019-20 (%)', 'Women (age 15-49) who are literate4 (%)', 'Women (age 15-49)  with 10 or more years of schooling (%)', 'Women age 20-24 years married before age 18 years (%)', 'Births in the 5 years preceding the survey that are third or higher order (%)', 'Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)', 'Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any method6 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any modern method6 (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Female sterilization (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Male sterilization (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - IUD/PPIUD (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Pill (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Condom (%)', 'Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Injectables (%)', 'Total Unmet need for Family Planning (Currently Married Women Age 15-49  years)7 (%)', 'Unmet need for spacing (Currently Married Women Age 15-49  years)7 (%)', 'Health worker ever talked to female non-users about family planning (%)', 'Current users ever told about side effects of current method of family planning8 (%)', 'Mothers who had an antenatal check-up in the first trimester  (for last birth in the 5 years before the survey) (%)', 'Mothers who had at least 4 antenatal care visits  (for last birth in the 5 years before the survey) (%)', 'Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%)', 'Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%)', 'Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%)', 'Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%)', 'Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)', 'Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.)', 'Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%)', 'Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)', 'Institutional births (in the 5 years before the survey) (%)', 'Institutional births in public facility (in the 5 years before the survey) (%)', 'Home births that were conducted by skilled health personnel  (in the 5 years before the survey)10 (%)', 'Births attended by skilled health personnel (in the 5 years before the survey)10 (%)', 'Births delivered by caesarean section (in the 5 years before the survey) (%)', 'Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%)', 'Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%)', "Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)", 'Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%)', 'Children age 12-23 months who have received BCG (%)', 'Children age 12-23 months who have received 3 doses of polio vaccine13 (%)', 'Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%)', 'Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%)', 'Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%)', 'Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%)', 'Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%)', 'Children age 9-35 months who received a vitamin A dose in the last 6 months (%)', 'Children age 12-23 months who received most of their vaccinations in a public health facility (%)', 'Children age 12-23 months who received most of their vaccinations in a private health facility (%)', 'Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%) ', 'Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%) ', 'Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%) ', 'Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%) ', 'Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%) ', 'Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)  ', 'Children under age 3 years breastfed within one hour of birth15 (%)', 'Children under age 6 months exclusively breastfed16 (%)', 'Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%)', 'Breastfeeding children age 6-23 months receiving an adequate diet16, 17  (%)', 'Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)', 'Total children age 6-23 months receiving an adequate diet16, 17  (%)', 'Children under 5 years who are stunted (height-for-age)18 (%)', 'Children under 5 years who are wasted (weight-for-height)18 (%)', 'Children under 5 years who are severely wasted (weight-for-height)19 (%)', 'Children under 5 years who are underweight (weight-for-age)18 (%)', 'Children under 5 years who are overweight (weight-for-height)20 (%)', 'Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)', 'Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%)', 'Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%)', 'Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)', 'Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%)', 'Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%)', 'All women age 15-49 years who are anaemic22 (%)', 'All women age 15-19 years who are anaemic22 (%) ', 'Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)', 'Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%)', 'Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)', 'Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%)', 'Men (age 15 years and above wih  very high (>160 mg/dl) Blood sugar level23 (%)', 'Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level  or taking medicine to control blood sugar level23 (%)', 'Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)', 'Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)', 'Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)', 'Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)', 'Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)', 'Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)', 'Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)', 'Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)', 'Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)', 'Women age 15 years and above who use any kind of tobacco (%)', 'Men age 15 years and above who use any kind of tobacco (%)', 'Women age 15 years and above who consume alcohol (%)', 'Men age 15 years and above who consume alcohol (%)']

In [14]:
geo_selected.dtypes

District                     object
State                        object
Low_BMI                     float64
Child_Anemia                 object
NonPregnant_Women_Anemia    float64
Women_Anemia                float64
dtype: object

In [15]:
numeric_cols = [
    "Low_BMI",
    "Child_Anemia",
    "NonPregnant_Women_Anemia",
    "Women_Anemia"
]

for col in numeric_cols:
    geo_selected[col] = pd.to_numeric(
        geo_selected[col],
        errors="coerce"
    )

C:\Users\hp\AppData\Local\Temp\ipykernel_11688\3581091346.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  geo_selected[col] = pd.to_numeric(

In [16]:
geo_selected.dtypes

District                     object
State                        object
Low_BMI                     float64
Child_Anemia                float64
NonPregnant_Women_Anemia    float64
Women_Anemia                float64
dtype: object

In [17]:
geo_selected[numeric_cols].isnull().sum()

Low_BMI                     0
Child_Anemia                2
NonPregnant_Women_Anemia    0
Women_Anemia                0
dtype: int64

In [18]:
for col in numeric_cols:
    geo_selected[col] = pd.to_numeric(
        geo_selected[col],
        errors="coerce"
    )

C:\Users\hp\AppData\Local\Temp\ipykernel_11688\806716342.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  geo_selected[col] = pd.to_numeric(

In [19]:
geo_selected[numeric_cols] = geo_selected[numeric_cols].fillna(
    geo_selected[numeric_cols].median()
)

C:\Users\hp\AppData\Local\Temp\ipykernel_11688\141255819.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  geo_selected[numeric_cols] = geo_selected[numeric_cols].fillna(

In [20]:
geo_selected["Geo_Risk"] = (
    0.50 * geo_selected["Women_Anemia"]
    + 0.30 * geo_selected["Child_Anemia"]
    + 0.20 * geo_selected["Low_BMI"]
)

C:\Users\hp\AppData\Local\Temp\ipykernel_11688\3882041596.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  geo_selected["Geo_Risk"] = (