In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [3]:
from pathlib import Path
import pandas as pd

# Go one folder above "notebooks"
PROJECT_ROOT = Path.cwd().parent

print("PROJECT_ROOT:", PROJECT_ROOT)

image_df = pd.read_csv(PROJECT_ROOT / "data" / "processed" / "train.csv")
clinical_df = pd.read_csv(PROJECT_ROOT / "data" / "clinical" / "anemia.csv")

print("Image Samples   :", len(image_df))
print("Clinical Samples:", len(clinical_df))

image_df.head()

PROJECT_ROOT: c:\Users\hp\Documents\Anemia_Fusion_Net_project
Image Samples   : 603
Clinical Samples: 1421

,image_path,country,label,filename,patient_folder
0,Italy\103\T_72_20190613_083940.jpg,Italy,0,T_72_20190613_083940.jpg,103
1,Italy\57\T_26_20190608_094356.jpg,Italy,0,T_26_20190608_094356.jpg,57
2,India\4\20200124_160522.jpg,India,1,20200124_160522.jpg,4
3,Italy\6\006_forniceal.png,Italy,0,006_forniceal.png,6
4,India\58\20200219_195511_palpebral.png,India,1,20200219_195511_palpebral.png,58

In [4]:
image_df["Geo"] = image_df["country"].map({
    "India": 0,
    "Italy": 1
})

image_df[["country", "Geo"]].head()

  country  Geo
0   Italy    1
1   Italy    1
2   India    0
3   Italy    1
4   India    0

In [5]:
fusion_df = image_df.copy()

clinical_columns = [
    "Gender",
    "Hemoglobin",
    "MCH",
    "MCHC",
    "MCV"
]

fusion_df[clinical_columns] = clinical_df.loc[
    :len(fusion_df)-1,
    clinical_columns
].values

fusion_df.head()

,image_path,country,label,filename,patient_folder,Geo,Gender,Hemoglobin,MCH,MCHC,MCV
0,Italy\103\T_72_20190613_083940.jpg,Italy,0,T_72_20190613_083940.jpg,103,1,1.0,14.9,22.7,29.1,83.7
1,Italy\57\T_26_20190608_094356.jpg,Italy,0,T_26_20190608_094356.jpg,57,1,0.0,15.9,25.4,28.3,72.0
2,India\4\20200124_160522.jpg,India,1,20200124_160522.jpg,4,0,0.0,9.0,21.5,29.6,71.2
3,Italy\6\006_forniceal.png,Italy,0,006_forniceal.png,6,1,0.0,14.9,16.0,31.4,87.5
4,India\58\20200219_195511_palpebral.png,India,1,20200219_195511_palpebral.png,58,0,1.0,14.7,22.0,28.2,99.5

In [6]:
fusion_df = fusion_df[
    [
        "image_path",
        "country",
        "Geo",
        "Gender",
        "Hemoglobin",
        "MCH",
        "MCHC",
        "MCV",
        "label",
        "filename",
        "patient_folder"
    ]
]

fusion_df.head()

,image_path,country,Geo,Gender,Hemoglobin,MCH,MCHC,MCV,label,filename,patient_folder
0,Italy\103\T_72_20190613_083940.jpg,Italy,1,1.0,14.9,22.7,29.1,83.7,0,T_72_20190613_083940.jpg,103
1,Italy\57\T_26_20190608_094356.jpg,Italy,1,0.0,15.9,25.4,28.3,72.0,0,T_26_20190608_094356.jpg,57
2,India\4\20200124_160522.jpg,India,0,0.0,9.0,21.5,29.6,71.2,1,20200124_160522.jpg,4
3,Italy\6\006_forniceal.png,Italy,1,0.0,14.9,16.0,31.4,87.5,0,006_forniceal.png,6
4,India\58\20200219_195511_palpebral.png,India,0,1.0,14.7,22.0,28.2,99.5,1,20200219_195511_palpebral.png,58

In [7]:
save_path = PROJECT_ROOT / "data" / "processed" / "fusion_data.csv"

fusion_df.to_csv(save_path, index=False)

print("Fusion Dataset Saved Successfully!")
print(save_path)

Fusion Dataset Saved Successfully!
c:\Users\hp\Documents\Anemia_Fusion_Net_project\data\processed\fusion_data.csv

In [8]:
fusion_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603 entries, 0 to 602
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   image_path      603 non-null    object
 1   country         603 non-null    object
 2   Geo             603 non-null    int64
 3   Gender          603 non-null    float64
 4   Hemoglobin      603 non-null    float64
 5   MCH             603 non-null    float64
 6   MCHC            603 non-null    float64
 7   MCV             603 non-null    float64
 8   label           603 non-null    int64
 9   filename        603 non-null    object
 10  patient_folder  603 non-null    int64
dtypes: float64(5), int64(3), object(3)
memory usage: 51.9+ KB

In [9]:
fusion_df.isnull().sum()

image_path        0
country           0
Geo               0
Gender            0
Hemoglobin        0
MCH               0
MCHC              0
MCV               0
label             0
filename          0
patient_folder    0
dtype: int64